version: '2'
services:
  craft-config-builder:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${GOPATH}/src/craft-config:/go/src/craft-config

    image: 033441544097.dkr.ecr.us-east-1.amazonaws.com/craft-config-builder
    container_name: craft-config-builder
    environment: 
      - GOOS=linux
      - GOARCH=amd64